id: P003042
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG14725
  title: སྒྲུང་རྩོམ་ཕྱོགས་བསྒྲིགས།
  author: ''
  volumes:
    d2119489a697418897a514b77a489a1a:
      image_group_id: I2PD18287
      title: ''
      volume_number: 1
      total_pages: 378
      base_file: v001.txt
